install:
	pip install -r requirements.txt

run:
	python manage.py runserver

migrate:
	python manage.py migrate

makemigrations:
	python manage.py makemigrations

createsuperuser:
	python manage.py createsuperuser

clean:
	find . -name '*.pyc' -delete
	find . -name '__pycache__' -delete